# Lecteur VLC intégré (MKV, AVI, MPEG-TS…) : pod officiel VideoLAN.
platform :ios, '17.0'
project 'OndeTV.xcodeproj'

target 'OndeTV' do
  pod 'MobileVLCKit', '~> 3.7'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
